name: Print Secret Key

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print secret key
        run: echo "MY_SECRET_KEY is ${{ secrets.MY_SECRET_KEY }}"
